name: Publish to Test PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  test_pypi_release:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - run: poetry install
      - run: poetry run pytest
      - run: poetry build
      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: poetry publish --dry-run
      - name: Publish package
        run: poetry publish -r testpypi --username __token__ --password ${{ secrets.TEST_PYPI_API_KEY }}